name: npu-chat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - nncf==2.14.1
      - onnx==1.17.0
      - optimum-intel==1.22.0
      - openvino==2025.3
      - openvino-tokenizers==2025.3
      - openvino-genai==2025.3
